# Version of the ROM
REVENGEOS_CODENAME := Pizza
REVENGEOS_REVISION := 2.0

ifndef REVENGEOS_BUILDTYPE
  REVENGEOS_BUILDTYPE := UNOFFICIAL
endif

TARGET_PRODUCT_SHORT := $(TARGET_PRODUCT)
TARGET_PRODUCT_SHORT := $(subst revengeos_,,$(TARGET_PRODUCT_SHORT))

REVENGEOS_VERSION := $(REVENGEOS_REVISION)-$(REVENGEOS_CODENAME)-$(REVENGEOS_BUILDTYPE)-$(TARGET_PRODUCT_SHORT)-$(shell date -u +%Y%m%d-%H%M)

PRODUCT_BUILD_PROP_OVERRIDES += BUILD_DISPLAY_ID="$(BUILD_ID)-$(shell whoami)@$(shell hostname)"

# Apply it to build.prop
PRODUCT_PROPERTY_OVERRIDES += \
    ro.modversion=RevengeOS-$(REVENGEOS_VERSION) \
    ro.revengeos.version=$(REVENGEOS_VERSION)
